package de.tukl.programmierpraktikum2021.mp2;

public class Util {
    public static final String[] exceptions = {
            "as", "the", "a", "of", "in", "to", "an", "and", "or", "with", "for",
            "als", "mit", "und", "vom", "zur", "der", "die", "das"
    };

    public static final Book[] books = {
            new Book("The design and analysis of computer algorithms", "Aho, Alfred V. and Hopcroft, John E. and Ullman, Jeffrey D.", 1974),
            new Book("Data Structures and Algorithms", "Aho, Alfred V. and Hopcroft, John E. and Ullman, Jeffrey D.", 1983),
            new Book("Structure and Implementation of Computer Programms", "Abelson, Harold and Sussman, Gerald J.", 1987),
            new Book("Compilers Principles Techniques and Tools", "Aho, Alfred V. and Lam, Monica S. and Sethi, Ravi and Ullman, Jeffrey D.", 2006),
            new Book("Compilers Principles Techniques and Tools", "Aho, Alfred V. and Sethi, Ravi and Ullman, Jeffrey D.", 1986),
            new Book("Proofs from THE BOOK", "Aigner, M. and Ziegler, G. M.", 2004),
            new Book("An Introduction to Mathematical Logic and Type Theory To Truth Through Proof", "Andrews, Peter B.", 1986),
            new Book("Category Theory", "Awodey, Steve", 2010),
            new Book("Text Compression", "Bell, Timothy C. and Cleary, John G. and Witten, Ian H.", 1990),
            new Book("Algorithmische Sprache und Programmentwicklung", "Bauer, F.L. and Woessner, H.", 1981),
            new Book("Category Theory for Computing Science", "Barr, Michael and Wells, Charles", 1999),
            new Book("The Lambda Calculus Its Syntax and Semantics", "Barendregt, H. P.", 1981),
            new Book("Algebra of Programming", "Bird, Richard and de Moor, Oege", 1997),
            new Book("Introduction to Functional Programming", "Bird, Richard and Wadler, Philip", 1988),
            new Book("Pearls of Functional Algorithm Design", "Bird, Richard", 2010),
            new Book("Thinking Functionally with Haskell", "Bird, Richard", 2014),
            new Book("Introduction to Functional Programming using Haskell", "Bird, Richard", 1998),
            new Book("Berechenbarkeit Komplexitaet Logik", "Boerger, Egon", 1985),
            new Book("Pascal for Mikrocomputer", "Bowles, Kenneth L.", 1982),
            new Book("The Mental Representation of Grammatical Relations", "Bresnan, Joan and Kaplan, Ronald M.", 1982),
            new Book("Deduktive Datenbanken Eine Einfuehrung aus der Sicht der logischen Programmierung", "Cremers, Armin B. and Griefahn, Ulrike and Hinze, Ralf", 1994),
            new Book("Introduction to Algorithms", "Cormen, Thomas H. and Leiserson, Charles E. and Rivest, Ronald L. and Stein, Clifford", 2001),
            new Book("Introduction to Algorithms", "Cormen, Thomas H. and Leiserson, Charles E. and Rivest, Ronald L.", 1990),
            new Book("Symbolic Logic and Mechanical Theorem Proving", "Chang, Chin-Liang and Lee, Richard Char-Tung", 1973),
            new Book("Einfuehrung in die Informatik", "Claus, Volker", 1975),
            new Book("Categories for Types", "Crole, Roy L.", 1994),
            new Book("Combinatory Logic Volume 1", "Curry, H.B. and Feys, R.", 1958),
            new Book("Categorical Combinators Sequential Algorithms and Functional Programming", "Curien, P.-L.", 1986),
            new Book("Introduction to Lattices and Order", "Davey, B.A. and Priestley, H.A.", 2002),
            new Book("Introduction to Lattices and Order", "Davey, B.A. and Priestley, H.A.", 1990),
            new Book("Compiling Functional Languages", "Diller, Antoni", 1988),
            new Book("Graphentheorie fuer Informatiker", "Doerfler, Willibald and Muehlbacher, Joerg", 1973),
            new Book("Einfuehrung in die Mathematik fuer Informatiker", "Doerfler, Willibald and Peschek, Werner", 1988),
            new Book("Equational Logic as a Programming Language", "O'Donnell, Michael J.", 1985),
            new Book("Einfuehrung in die mathematische Logik", "Ebbinghaus, Heinz-Dieter and Flum, Joerg and Thomas, Wolfgang", 1986),
            new Book("Interlisp Programmierhandbuch 4. Auflage", "Epp, Berthold", 1981),
            new Book("Graph Algorithms", "Even, Shimon", 1979),
            new Book("Semantik von Programmiersprachen", "Fehr, Elfriede", 1989),
            new Book("A Compendium of Continuous Lattices", "Gierz, G. and Hofmann, K.H. and Keimel, K and Lawson, J.D. and Mislove, M. and Scott, D.S.", 1980),
            new Book("Concrete mathematics", "Graham, Ronald L. and Knuth, Donald E. and Patashnik, Oren", 1994),
            new Book("Logic for Computer Science Foundations of Automatic Theorem Proving", "Gallier, Jean H.", 1986),
            new Book("Computers and Intractability A Guide to NP-Completeness", "Garey, Michael R. and Johnson, David S.", 1979),
            new Book("Principles of Functional Programming", "Glaser, Hugh and Hankin, Chris and Till, David", 1984),
            new Book("Topologie algebrique et theorie des faisceaux", "Godemont, Roger", 1958),
            new Book("TOPOI The Categorical Analysis of Logic", "Goldblatt, Robert", 1979),
            new Book("The Science of Programming", "Gries, David", 1981),
            new Book("Datenstrukturen und Algorithmen", "Gueting, Ralf Hartmut", 1992),
            new Book("ELAN-Handbuch 2. korr. Auflage", "Hahn, Rainer and Stock, Peters", 1982),
            new Book("Einfuehrung in das Programmieren in LISP", "Hamann, Christian-M.", 1982),
            new Book("A Concurrent PASCAL Compiler for minicomputers", "Hartmann, Alfred C.", 1977),
            new Book("Functional Programming Application and Implementation", "Henderson, Peter", 1980),
            new Book("Einfuehrung in die funktionale Programmierung mit Miranda", "Hinze, Ralf", 1992),
            new Book("Functional Programming with Miranda", "Holyer, Ian", 1991),
            new Book("Problemloesen und Programmieren mit LOGO", "Hoppe, Heinz Ulrich and Loethe, Herbert", 1984),
            new Book("Informatik  Rechenanlagen", "Hotz, G.", 1972),
            new Book("Schaltkreistheorie", "Hotz, G.", 1974),
            new Book("Combinatorial Algorithms", "Hu, T.C.", 1982),
            new Book("The Haskell School of Expression Learning Functional Programming through Multimedia", "Hudak, Paul", 2000),
            new Book("APL A Programming Language", "Iverson, Kenneth E.", 1962),
            new Book("Introduction to Expert Systems", "Jackson, Peter", 1986),
            new Book("Pascal User Manual and Report", "Jensen, Kathleen and Wirth, Niklaus", 1978),
            new Book("Pascal User Manual and Report", "Jensen, Kathleen and Wirth, Niklaus", 1985),
            new Book("Qualified Types Theory and Practice", "Jones, Mark P.", 1994),
            new Book("Mathematics and the Imagination", "Kasner, Edward and Newman, James", 1949),
            new Book("Die Geschichte der Null", "Kaplan, Robert", 2000),
            new Book("Programmieren in C", "Kernighan, Brian W. and Ritchie, Dennis M.", 1983),
            new Book("The Art of Computer Programming Volume 4 Fascicle 2 Generating All Tuples and Permutations", "Knuth, Donald E.", 2005),
            new Book("The Art of Computer Programming Volume 4 Fascicle 3 Generating All Combinations and Partitions", "Knuth, Donald E.", 2005),
            new Book("The Art of Computer Programming Volume 1 Fundamental Algorithms", "Knuth, Donald E.", 1997),
            new Book("The Art of Computer Programming Volume 2 Seminumerical Algorithms", "Knuth, Donald E.", 1997),
            new Book("The Art of Computer Programming Volume 3 Sorting and Searching", "Knuth, Donald E.", 1998),
            new Book("The Art of Computer Programming Volume 1 Fundamental Algorithms", "Knuth, Donald E.", 1968),
            new Book("The Art of Computer Programming Volume 2 Seminumerical Algorithms", "Knuth, Donald E.", 1969),
            new Book("The Art of Computer Programming Volume 3 Sorting and Searching", "Knuth, Donald E.", 1973),
            new Book("The Foundations of Program Verification", "Loeckx, Jacques and Sieber, Kurt and Stansifer, Ryan D.", 1984),
            new Book("LaTeX A document preparation system", "Lamport, Leslie", 1994),
            new Book("6502 Programmieren in Assembler", "Leventhal, Lance A.", 1981),
            new Book("Elements of the Theory of Computing", "Lewis, Harry R. and Papadimitriou, Christos H.", 1981),
            new Book("Foundations of Logic Programming", "J.W., Lloyd", 1984),
            new Book("Foundations of Logic Programming", "Lloyd, John W.", 1987),
            new Book("The Definition of Standard ML", "Milner, Robin and Tofte, Mads and Harper, Robert", 1990),
            new Book("The Definition of Standard ML (Revised)", "Milner, Robin and Tofte, Mads and Harper, Robert and MacQueen, David", 1997),
            new Book("Computing with Logic Logic Programming with Prolog", "Maier, David and Warren, David S.", 1988),
            new Book("Categories for Working Mathematicians", "Mac Lane, Saunders", 1970),
            new Book("Categories for the Working Mathematician", "Mac Lane, Saunders", 1998),
            new Book("Functional programming Practice and Theory", "MacLennan, Bruce", 1990),
            new Book("The Theory of Relational Databases", "Maier, David", 1983),
            new Book("Datenstrukturen und Programmierverfahren", "Maurer, H.", 1974),
            new Book("Effiziente Algorithmen", "Mehlhorn, K.", 1977),
            new Book("Data Structures and Algorithms 3 Multi-dimensional Searching and Computational Geometry", "Mehlhorn, Kurt", 1984),
            new Book("Datenstrukturen und effiziente Algorithmen Band 1 Sortieren und Suchen", "Mehlhorn, Kurt", 1988),
            new Book("Programming in Prolog", "Mellish, C.S. and Clocksin, W.F.", 1995),
            new Book("Communication and Concurrency", "Milner, Robin", 1989),
            new Book("Foundations for Programming Languages", "Mitchell, John C.", 1996),
            new Book("Softwaretechnik Methodisches Programmieren im Grossen", "Nagl, Manfred", 1990),
            new Book("Purely Functional Data Structures", "Okasaki, Chris", 1998),
            new Book("Specification and Transformation of Programs A Formal Approach to Software Development", "Partsch, Helmut A.", 1990),
            new Book("ML for the working programmer", "Paulson, L. C.", 1991),
            new Book("ML for the Working Programmer", "Paulson, L. C.", 1996),
            new Book("The Beauty of Fractals", "Peitgen, Heinz-Otto and Richter, Peter H.", 1986),
            new Book("Implementing functional languages a tutorial", "Peyton Jones, S.L. and Lester, D.R.", 1992),
            new Book("Types and programming languages", "Pierce, Benjamin C.", 2002),
            new Book("Basic Category Theory for Computer Scientists", "Pierce, Benjamin C.", 1991),
            new Book("Das C-Lernbuch", "Plum, Thomas", 1985),
            new Book("Natural Deduction A Proof-Theoretical Study", "Prawitz, Dag", 1965),
            new Book("Die Programmiersprache Ada", "Pyle, Ian C.", 1981),
            new Book("Algorithms a Functional Programming Approach", "Rabhi, Fethi and Lapalme, Guy", 1999),
            new Book("Elements of Functional Programming", "Reade, Chris", 1989),
            new Book("Betriebssysteme", "Richter, Lutz", 1977),
            new Book("Computational Category Theory", "Rydeheard, David E. and Burstall, Rod M.", 1988),
            new Book("Haskell 98 Language and Libraries", "Peyton Jones, Simon", 2003),
            new Book("Computation and Automata", "Salomaa, Arto", 1985),
            new Book("Compiler Aufbau und Arbeitsweise", "Schneider, Hans Juergen", 1975),
            new Book("Strategiespiele Computerorientierte Einfuehrung in die Algorithmen der Spieltheorie", "Schrage, Georg and Baumann, Ruedeger", 1984),
            new Book("Algorithmen in C", "Sedgewick, Robert", 1992),
            new Book("Formalisieren und Beweisen Logik fuer Informatiker", "Siefkes, Dirk", 1990),
            new Book("Software Engineering", "Sommerville, Ian", 1989),
            new Book("Arithmetik in Rechenanlagen", "Spaniol, Otto", 1976),
            new Book("Combinators Lambda-Terms and Proof Theory", "Stenlund, Soeren", 1972),
            new Book("Einfuehrung in die kuenstliche Intelligenz", "Stede, Manfred", 1983),
            new Book("The Art of Prolog Advanced Programming Techniques", "Sterling, Leon and Shapiro, Ehud", 1986),
            new Book("The Magical Maze Seeing the World Through Mathematical Eyes", "Stewart, Ian", 1999),
            new Book("Denotational Semantics The Scott-Strachey Approach to Programming Language Theory", "Stoy, Joseph E.", 1977),
            new Book("The C++ Programming Language", "Stroustrup, Bjarne", 1986),
            new Book("Practical Foundations of Mathematics", "Taylor, Paul", 1999),
            new Book("Semantics of Programming Languages", "Tennent, R.D.", 1991),
            new Book("Haskell The Craft of Functional Programming", "Thompson, Simon", 1996),
            new Book("Haskell The Craft of Functional Programming", "Thompson, Simon", 1999),
            new Book("Constructivism in Mathematics An Introduction", "Troelstra, A.S. and van Dalen, D.", 1988),
            new Book("Mikroprozessoren vom Bauteil zur Anwendung", "Waller, Heinz and Hilgers, Peter", 1980),
            new Book("Effiziente Algorithmen fuer grundlegende Funktionen", "Wegener, I.", 1989),
            new Book("Functional Programming Using Standard ML", "Wikstroem, Ake", 1987),
            new Book("Algorithmen und Datenstrukturen", "Wirth, Niklaus", 1979),
            new Book("Data Structures Algorithms and Performance", "Wood, Derick", 1993),
            new Book("Abstract Interpretation of Declarative Languages", "Abramsky, Samson and Hankin, Chris", 1987),
            new Book("Functional Programming", "Field, Anthony J. and Harrison, Peter G.", 1988),
            new Book("The Implementation of Functional Programming Languages", "Peyton Jones, Simon", 1987)
    };
}
