MP1:
  image: openjdk:11
  script:
    - cd MP1
    - ./gradlew test
  artifacts:
    paths:
      - MP1/build/reports
    when: always
    expire_in: 2 weeks
  rules:
    - changes:
      - MP1/**/*
